### ISSUE TITLE
Question: is there a way to specify the channel in conda-requirements.txt

### ISSUE THREAD

**Issue by birdsarah** [kennethreitz/conda-buildpack#11]
Hi, sorry if this is the wrong place for it, I'm wondering if there's a place to specify the package channel to do the equivalent of:

    conda install --channel USERNAME PACKAGE

many thanks, sarah bird

**Comment by kennethreitz** [comment]
not at this time.

**Comment by talumbau** [comment]
I would be +1 on such a feature, as a I forked this repo to get such a feature and modified this line:

https://github.com/kennethreitz/conda-buildpack/blob/master/bin/steps/conda_compile#L13

```
conda install --file conda-requirements.txt --yes | indent
```

to hard code my desired channel.
