### ISSUE TITLE
ImportError: No module named 'conda' is caused in Python3

### ISSUE THREAD

**Issue by icoxfog417** [kennethreitz/conda-buildpack#14]
(It is also mentioned in #7 ),

The above error will arise if you use conda-buildpack with Python3.
But you can avoid this error by adding the below statements in `conda-requirements.txt` (the versions depends on your environment).

```
conda=3.10.1=py34_0
conda-env=2.1.4=py34_0
requests=2.6.0=py34_0
```

So this error will be caused by Python2 `conda` that is initially installed in the deploy process.

I think we have to consider the `runtime.txt` to choose the conda version (Python2 or Python3).

**Comment by amelio-vazquez-reina** [comment]
I am having the same problem.

**Comment by kennethreitz** [comment]
Python 3 is not currently supported.

**Comment by icoxfog417** [comment]
@kennethreitz 

I think Python 3 will be supported if #8 is implemented. Do you have any plan for finishing #8 implementation?
