### ISSUE TITLE
Not compatible with whitenoise?

### ISSUE THREAD

**Issue by davesque** [kennethreitz/conda-buildpack#22]
I recently switched to using the conda buildpack and now my app no longer serves static files correctly (404 responses for static assets).  I'm using [whitenoise](https://pypi.python.org/pypi/whitenoise) to serve static files.  Any ideas about how I could troubleshoot this?

**Comment by kennethreitz** [comment]
This buildpack doesn't run collectstatic automatically for you.

**Comment by davesque** [comment]
I tried running collectstatic and it made no difference.

**Comment by kennethreitz** [comment]
How did you run it?

**Comment by davesque** [comment]
`heroku run python manage.py collectstatic`

**Comment by kennethreitz** [comment]
You need to add that as a  part of your Procfile, unfortunately. 

    web: python manage.py collectstatic; mywebserver

**Comment by davesque** [comment]
Cool.  That worked.

I actually had to use `web: python manage.py collectstatic --noinput; webservercmd`.

Are there any special considerations when using this approach or is it pretty standard to put collectstatic in the `Procfile`?

**Comment by kennethreitz** [comment]
No special considerations. It's pretty standard, as your web process requires that collectstatic be run before starting up. Ideally, this would happen in the buildpack (like it is in the Python buildpack), but this buildpack is far less fancy.

**Comment by davesque** [comment]
Cool, thx!
