### ISSUE TITLE
Can't build scipy - "#include <ffi.h>" fails

### ISSUE THREAD

**Issue by eli-b** [kennethreitz/conda-buildpack#24]
Trying to deploy to heroku with `scipy==0.14.0` in the conda-requirements.txt file yields this error:

gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/app/.heroku/miniconda/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o

c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

include <ffi.h>

^

compilation terminated.

error: command 'gcc' failed with exit status 1

The issue came up in the following SO question too: http://stackoverflow.com/questions/35775048/scipy-on-heroku-with-conda-failing-to-deploy

**Comment by dracos** [comment]
You need to install the `libffi-dev` (or your OS's equivalent) system package; on debian/ubuntu, that would be `apt-get install libffi-dev`, for example.

**Comment by eli-b** [comment]
Thanks @dracos. @github-account-because-they-want-it, if this is still relevant for you, you may want to try @dracos's suggestion.
