### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by d10** [kennethreitz/conda-buildpack#7]
```
Traceback (most recent call last):
  File "/app/.heroku/miniconda/bin/conda", line 3, in <module>
    from conda.cli import main
ImportError: No module named 'conda'
```

See https://travis-ci.org/wei2912/bce-simulation/builds/44591616.

**Comment by kennethreitz** [comment]
Interesting. You may want to try purging your application's build cache and see if this resolves the problem. 

you can use the `heroku repo:purge_cache` command, available with this heroku plugin:
https://github.com/heroku/heroku-repo

**Comment by birdsarah** [comment]
Hi, @kennethreitz. Thanks for maintaining this. 

I was having the same issue:

````bash
Traceback (most recent call last):
  File "/app/.heroku/miniconda/bin/conda", line 3, in <module>
    from conda.cli import main
ImportError: No module named 'conda'

 !     Push rejected, failed to compile Python/Conda app
````

I switched to Python 2, (not Python 3) packages and it worked.

**Comment by kennethreitz** [comment]
@birdsarah this was caused by using python3?

**Comment by d10** [comment]
Could be. I encountered this issue when I switched to Python 3 too. I eventually switched back to Python 2, and it worked.

**Comment by kennethreitz** [comment]
How did you switch to python 3?

**Comment by d10** [comment]
I updated the conda-requirements.txt file to install Python 3.

**Comment by birdsarah** [comment]
I guess there's a lot going on right now, because I have actually forgotten! 

I believe it was in the conda-requirements file. This buildpack, to my understanding, doesn't use the runtime.txt so I can't imagine what else I would have done.

**Comment by asmeurer** [comment]
What exactly did you put in the `conda-requirements.txt` file? conda should always keep itself correctly installed, even if you change python versions.

**Comment by icoxfog417** [comment]
About #14

The error arose at `from conda.cli import main` (it is not the problem of command line tool, but the python code).
I don't know exactly what, but I thought we need Python3 conda environment package to run the script.
